import '../../../public/customer/js/bootstrap.bundle.min.js';
import '../../../public/customer/js/tiny-slider.js';
import '../../../public/customer/js/flatpickr.min.js';
import '../../../public/customer/js/aos.js';
import '../../../public/customer/js/glightbox.min.js';
import '../../../public/customer/js/navbar.js';
import '../../../public/customer/js/counter.js';
import '../../../public/customer/js/custom.js';
import '../../../public/customer/js/iziToast.min.js';
